ruleDirs:
  - rules
testConfigs:
  - testDir: rules-tests
customLanguages:
  typst:
    libraryPath:
      x86_64-unknown-linux-gnu: tree-sitter-typst.so
      x86_64-pc-windows-msvc: tree-sitter-typst.dll
    extensions: [typ]
    expandoChar: Î¼
